"""
Objective strength measurement for the MCTS engine.

This project has never had one. arena.py cannot instantiate MCTSPlayer at all, the
trainer has no held-out split, and the logged p_loss is in-sample — so "is the engine
stronger than it was?" has never been answerable. Everything in Track B (the mate-in-1
blunder fix, PUCT/FPU, int8 quantisation, time budgets, a smaller trunk) changes move
selection, and none of it can be shipped responsibly without this.

Metric: average centipawn loss (ACPL) against Stockfish at fixed depth.

    loss = max(0, eval_before - eval_after)     both from the mover's perspective

Two properties make the comparison trustworthy:

  * PAIRED. Both arms are measured on the identical frozen position set, so the
    comparison is on per-position differences and the (large) variation between
    positions cancels instead of drowning the effect.
  * DETERMINISTIC. Stockfish is sent ucinewgame before every analysis. Without it the
    transposition table persists and the same position scores 48/47/51 cp on repeat
    calls; with it, the same value every time.

Positions are generated by letting Stockfish play both sides at shallow depth with
randomised top-k selection, so they are real middlegames rather than random-legal-move
noise, and every position's baseline eval and best move are cached at build time. That
halves the Stockfish work per arm and keeps the reference fixed across runs.

Beware underpowered results. Per-position loss has a standard deviation near 90cp, so
a 50-position run cannot resolve anything; `compare` always prints the N required for
the variance it actually observed. Treat a non-significant result as "not measured",
never as "no difference".

Usage:
    python bench/strength.py build --games 700 --mate 120
    python bench/strength.py run baseline-600 --sims 600
    python bench/strength.py run candidate-600 --sims 600
    python bench/strength.py compare baseline-600 candidate-600
    python bench/strength.py mate baseline --sims 200
"""

import argparse
import json
import math
import os
import random
import sys
import time
from multiprocessing import Pool

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

import chess  # noqa: E402
import chess.engine  # noqa: E402

SF_PATH = os.path.join(ROOT, "stockfish", "stockfish.exe")
SUITE_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "suites")
RESULTS_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "results")

REF_DEPTH = 16          # Stockfish reference depth for scoring
GEN_DEPTH = 6           # shallow depth used only to generate realistic games
MIN_PIECES = 12         # stay clear of the <=7-piece tablebase HTTP probe
MIN_LEGAL = 8
MAX_LEGAL = 48
BLUNDER_CP = 200        # a "blunder" for reporting purposes
LOSS_CAP = 1000         # cap so a single mate score cannot dominate the mean
MATE_SCORE = 100000


# ---------------------------------------------------------------------------
# Stockfish helpers
# ---------------------------------------------------------------------------

def open_engine(hash_mb: int = 32):
    eng = chess.engine.SimpleEngine.popen_uci(SF_PATH)
    eng.configure({"Threads": 1, "Hash": hash_mb})
    return eng


def analyse(eng, board, depth=REF_DEPTH, multipv=None):
    """
    Analyse at fixed depth with a CLEAN transposition table.

    The fresh `game` object makes python-chess send ucinewgame, which is what makes
    the result reproducible; without it repeated analyses of one position disagree by
    several centipawns because the TT carries over.
    """
    kwargs = {"game": object()}
    if multipv:
        kwargs["multipv"] = multipv
    return eng.analyse(board, chess.engine.Limit(depth=depth), **kwargs)


def pov_cp(info, board):
    """Score in centipawns from the perspective of the side to move on `board`."""
    return info["score"].pov(board.turn).score(mate_score=MATE_SCORE)


def rebuild(moves_uci):
    """Rebuild a board WITH its move stack (never chess.Board(fen) — see bench/positions.py)."""
    b = chess.Board()
    for u in moves_uci:
        b.push(chess.Move.from_uci(u))
    return b


def _playable(board):
    if board.is_game_over():
        return False
    if chess.popcount(board.occupied) < MIN_PIECES:
        return False
    return MIN_LEGAL <= board.legal_moves.count() <= MAX_LEGAL


# ---------------------------------------------------------------------------
# Suite construction
# ---------------------------------------------------------------------------

def _gen_game(eng, rng, max_ply):
    """
    Play one game with Stockfish choosing among its top-3 shallow moves at random.

    Random-legal play produces positions no real game would ever reach, which makes an
    ACPL number meaningless as an absolute. Shallow Stockfish with randomised top-k
    stays in plausible territory while still giving enough variety to fill a suite.
    """
    board = chess.Board()
    while len(board.move_stack) < max_ply and not board.is_game_over():
        n = min(3, board.legal_moves.count())
        if n == 0:
            break
        try:
            infos = analyse(eng, board, depth=GEN_DEPTH, multipv=n)
        except Exception:
            break
        moves = [i["pv"][0] for i in infos if i.get("pv")]
        if not moves:
            break
        # Weight toward the best move so games stay coherent, but not deterministically.
        weights = [0.6, 0.25, 0.15][:len(moves)]
        board.push(rng.choices(moves, weights=weights)[0])
    return board


def _build_chunk(args):
    """Worker: generate games from one seed range and return scored positions."""
    seed, n_games, per_game, want_mate = args
    rng = random.Random(seed)
    eng = open_engine()
    positions, mates = [], []
    try:
        for g in range(n_games):
            max_ply = rng.randint(20, 70)
            board = _gen_game(eng, rng, max_ply)
            history = board.move_stack[:]

            # Sample distinct plies from this game.
            candidates = []
            for _ in range(per_game * 3):
                if len(history) < 12:
                    break
                cut = rng.randint(12, len(history))
                sub = [m.uci() for m in history[:cut]]
                b = rebuild(sub)
                if _playable(b):
                    candidates.append((sub, b))
                if len(candidates) >= per_game:
                    break

            for sub, b in candidates[:per_game]:
                info = analyse(eng, b, depth=REF_DEPTH)
                pv = info.get("pv")
                if not pv:
                    continue
                positions.append({
                    "moves": sub,
                    "fen": b.fen(),
                    "ply": len(sub),
                    "n_legal": b.legal_moves.count(),
                    "n_pieces": chess.popcount(b.occupied),
                    "base_cp": pov_cp(info, b),
                    "sf_best": pv[0].uci(),
                })

            if want_mate:
                mates.extend(_gen_mate_positions(eng, rng))
    finally:
        eng.quit()
    return positions, mates


def _mate_in_1_moves(board):
    """All moves that deliver immediate checkmate. Cheap: push, test, pop."""
    out = []
    for mv in board.legal_moves:
        board.push(mv)
        if board.is_checkmate():
            out.append(mv.uci())
        board.pop()
    return out


def _gen_mate_positions(eng, rng, max_ply=120):
    """
    Produce positions where the side to move has mate in 1.

    Stockfish playing itself almost never allows one, so this pits a strong side
    (shallow Stockfish best move) against a weak side (random legal), which reaches
    mating attacks quickly. Positions are kept at >= 8 pieces so the engine's own
    search has to find the mate — below that, select_move short-circuits to the
    Lichess tablebase and the test would measure the network, not the engine.
    """
    found = []
    board = chess.Board()
    strong = rng.choice([chess.WHITE, chess.BLACK])
    while len(board.move_stack) < max_ply and not board.is_game_over():
        if board.turn == strong and chess.popcount(board.occupied) >= 8:
            mating = _mate_in_1_moves(board)
            if mating:
                found.append({
                    "moves": [m.uci() for m in board.move_stack],
                    "fen": board.fen(),
                    "mating_moves": mating,
                    "n_legal": board.legal_moves.count(),
                    "n_pieces": chess.popcount(board.occupied),
                })
                return found  # one per game keeps the sample independent

        if board.turn == strong:
            try:
                info = analyse(eng, board, depth=GEN_DEPTH)
                mv = info["pv"][0]
            except Exception:
                break
        else:
            mv = rng.choice(list(board.legal_moves))
        board.push(mv)
    return found


def build(n_games, per_game, want_mate, workers, seed=20260805):
    os.makedirs(SUITE_DIR, exist_ok=True)
    chunks = []
    per_worker = max(1, n_games // workers)
    for w in range(workers):
        chunks.append((seed + w * 7919, per_worker, per_game, want_mate))

    t0 = time.perf_counter()
    positions, mates = [], []
    with Pool(workers) as pool:
        for i, (p, m) in enumerate(pool.imap_unordered(_build_chunk, chunks)):
            positions.extend(p)
            mates.extend(m)
            print(f"  worker {i + 1}/{len(chunks)} done: "
                  f"{len(positions)} positions, {len(mates)} mate-in-1")

    # Deterministic order regardless of which worker finished first.
    positions.sort(key=lambda e: (len(e["moves"]), e["fen"]))
    mates.sort(key=lambda e: (len(e["moves"]), e["fen"]))
    for i, e in enumerate(positions):
        e["name"] = f"p{i:04d}"
    for i, e in enumerate(mates):
        e["name"] = f"m{i:04d}"

    with open(os.path.join(SUITE_DIR, "acpl.json"), "w") as f:
        json.dump({"ref_depth": REF_DEPTH, "positions": positions}, f)
    with open(os.path.join(SUITE_DIR, "mate1.json"), "w") as f:
        json.dump({"positions": mates}, f)

    dt = time.perf_counter() - t0
    plies = [e["ply"] for e in positions]
    print(f"\nbuilt {len(positions)} ACPL positions and {len(mates)} mate-in-1 positions "
          f"in {dt:.0f}s")
    if plies:
        print(f"  ply range {min(plies)}-{max(plies)}, median {sorted(plies)[len(plies)//2]}")
        print(f"  pieces {min(e['n_pieces'] for e in positions)}-"
              f"{max(e['n_pieces'] for e in positions)}, "
              f"legal {min(e['n_legal'] for e in positions)}-"
              f"{max(e['n_legal'] for e in positions)}")


def load_suite(name):
    path = os.path.join(SUITE_DIR, f"{name}.json")
    if not os.path.exists(path):
        raise SystemExit(f"no suite at {path} — run: python bench/strength.py build")
    with open(path) as f:
        return json.load(f)


# ---------------------------------------------------------------------------
# Measurement workers
# ---------------------------------------------------------------------------

_ENGINE = None
_MODEL = None
_SIMS = None
_UNIFORM = False


def _init_worker(sims, threads, uniform=False):
    global _ENGINE, _MODEL, _SIMS, _UNIFORM
    # Set BEFORE the ONNX session is created: with many workers, one inference thread
    # each is right — oversubscribing turns a parallel sweep into a slow serial one.
    os.environ["CHESS_NUM_THREADS"] = str(threads)
    _SIMS = sims
    _UNIFORM = uniform
    _ENGINE = open_engine()

    if uniform:
        # Deliberate control arm: search with no network at all (uniform priors).
        # It must come out clearly worse. If a comparison against this is NOT
        # significant, the harness lacks the power to detect anything and no null
        # result from it should be believed.
        os.environ["CHESS_USE_ONNX"] = "0"
        _MODEL = None
        return

    from inference import get_onnx_session
    session = get_onnx_session()
    model = None
    if session is None:
        from neural_network import load_dual_model, DEFAULT_CKPT_PATH
        model = load_dual_model(DEFAULT_CKPT_PATH)
    _MODEL = model
    if session is None and model is None:
        raise RuntimeError("no model available; refusing to measure a random policy")


def _make_player():
    """Mirror app.py: a fresh player per move, temperature 0, no Dirichlet noise."""
    from mcts import MCTSPlayer, MCTSConfig
    return MCTSPlayer(model=_MODEL,
                      config=MCTSConfig(num_simulations=_SIMS, temperature=0,
                                        add_noise=False))


def _acpl_one(entry):
    board = rebuild(entry["moves"])
    t0 = time.perf_counter()
    move = _make_player().select_move(board)
    ms = (time.perf_counter() - t0) * 1000
    if move is None:
        return None

    board.push(move)
    if board.is_checkmate():
        after_cp = MATE_SCORE          # we just delivered mate
    elif board.is_game_over():
        after_cp = 0                   # stalemate / insufficient material / etc
    else:
        after_cp = -pov_cp(analyse(_ENGINE, board), board)

    loss = min(LOSS_CAP, max(0, entry["base_cp"] - after_cp))
    return {
        "name": entry["name"],
        "move": move.uci(),
        "loss": loss,
        "agree": move.uci() == entry["sf_best"],
        "ms": round(ms, 1),
    }


def _mate_one(entry):
    board = rebuild(entry["moves"])
    t0 = time.perf_counter()
    move = _make_player().select_move(board)
    ms = (time.perf_counter() - t0) * 1000
    return {
        "name": entry["name"],
        "move": move.uci() if move else None,
        "found": bool(move) and move.uci() in entry["mating_moves"],
        "ms": round(ms, 1),
    }


def _run_pool(fn, entries, sims, workers, threads, label, uniform=False):
    t0 = time.perf_counter()
    out = []
    with Pool(workers, initializer=_init_worker,
              initargs=(sims, threads, uniform)) as pool:
        for i, r in enumerate(pool.imap_unordered(fn, entries, chunksize=1), 1):
            if r is not None:
                out.append(r)
            if i % 50 == 0 or i == len(entries):
                el = time.perf_counter() - t0
                rate = i / el
                print(f"  {i}/{len(entries)}  {el:5.0f}s elapsed, "
                      f"{(len(entries) - i) / rate:5.0f}s left", flush=True)
    out.sort(key=lambda r: r["name"])
    return out, time.perf_counter() - t0


# ---------------------------------------------------------------------------
# Statistics (no scipy in this venv)
# ---------------------------------------------------------------------------

def normal_cdf(z):
    return 0.5 * (1.0 + math.erf(z / math.sqrt(2.0)))


def summarize(losses):
    n = len(losses)
    mean = sum(losses) / n
    var = sum((x - mean) ** 2 for x in losses) / (n - 1) if n > 1 else 0.0
    sd = math.sqrt(var)
    return mean, sd, sd / math.sqrt(n) if n else 0.0


def n_for_delta(sd, delta, power=0.80, alpha=0.05):
    """Paired-sample N needed to detect `delta` given per-pair sd."""
    z_a, z_b = 1.959963985, 0.8416212336
    return math.ceil((z_a + z_b) ** 2 * sd ** 2 / delta ** 2)


# ---------------------------------------------------------------------------
# Commands
# ---------------------------------------------------------------------------

def cmd_run(label, sims, workers, threads, limit, uniform=False):
    suite = load_suite("acpl")
    entries = suite["positions"][:limit] if limit else suite["positions"]
    print(f"ACPL run '{label}': {len(entries)} positions, {sims} sims, "
          f"{workers} workers x {threads} thread(s), Stockfish depth {suite['ref_depth']}"
          + ("   [UNIFORM CONTROL: no network]" if uniform else ""))

    rows, dt = _run_pool(_acpl_one, entries, sims, workers, threads, label, uniform)
    losses = [r["loss"] for r in rows]
    mean, sd, se = summarize(losses)
    agree = sum(r["agree"] for r in rows) / len(rows) * 100
    blunders = sum(1 for x in losses if x >= BLUNDER_CP) / len(rows) * 100
    ms = sorted(r["ms"] for r in rows)

    out = {
        "label": label, "sims": sims, "n": len(rows), "uniform": uniform,
        "ref_depth": suite["ref_depth"],
        "acpl": round(mean, 2), "sd": round(sd, 2), "se": round(se, 2),
        "agreement_pct": round(agree, 2),
        "blunder_pct": round(blunders, 2),
        "median_ms": ms[len(ms) // 2],
        "wall_s": round(dt, 1),
        "rows": rows,
    }
    os.makedirs(RESULTS_DIR, exist_ok=True)
    with open(os.path.join(RESULTS_DIR, f"strength_{label}.json"), "w") as f:
        json.dump(out, f)

    print(f"\n  ACPL              {mean:8.1f} cp   (sd {sd:.1f}, se {se:.1f})")
    print(f"  Stockfish top-1   {agree:8.1f} %")
    print(f"  blunders >={BLUNDER_CP}cp   {blunders:8.1f} %")
    print(f"  median move time  {ms[len(ms)//2]:8.0f} ms")
    print(f"  wall clock        {dt:8.0f} s")
    # Upper bound only: this uses the spread of the losses themselves. Two similar
    # arms agree on most positions, so their paired DIFFERENCES have a much smaller
    # sd and need far fewer positions. `compare` reports the real figure.
    print(f"\n  <= {n_for_delta(sd, 20)} paired positions to resolve 20cp "
          f"(loose upper bound; compare reports the true N)")
    return out


def cmd_mate(label, sims, workers, threads, limit):
    suite = load_suite("mate1")
    entries = suite["positions"][:limit] if limit else suite["positions"]
    if not entries:
        raise SystemExit("mate suite is empty — rebuild with --mate")
    print(f"Mate-in-1 '{label}': {len(entries)} positions, {sims} sims")
    rows, dt = _run_pool(_mate_one, entries, sims, workers, threads, label)
    found = sum(r["found"] for r in rows)
    out = {"label": label, "sims": sims, "n": len(rows), "found": found,
           "pct": round(found / len(rows) * 100, 1), "wall_s": round(dt, 1),
           "rows": rows}
    os.makedirs(RESULTS_DIR, exist_ok=True)
    with open(os.path.join(RESULTS_DIR, f"mate_{label}.json"), "w") as f:
        json.dump(out, f)
    print(f"\n  mate-in-1 found   {found}/{len(rows)}  ({out['pct']}%)")
    print(f"  wall clock        {dt:.0f} s")
    return out


def cmd_compare(a_label, b_label):
    def load(l):
        p = os.path.join(RESULTS_DIR, f"strength_{l}.json")
        if not os.path.exists(p):
            raise SystemExit(f"missing {p}")
        with open(p) as f:
            return json.load(f)

    a, b = load(a_label), load(b_label)
    amap = {r["name"]: r for r in a["rows"]}
    bmap = {r["name"]: r for r in b["rows"]}
    shared = sorted(set(amap) & set(bmap))
    if not shared:
        raise SystemExit("no shared positions between the two runs")

    diffs = [bmap[n]["loss"] - amap[n]["loss"] for n in shared]
    mean, sd, se = summarize(diffs)
    t = mean / se if se else 0.0
    p = 2 * (1 - normal_cdf(abs(t)))
    lo, hi = mean - 1.96 * se, mean + 1.96 * se
    changed = sum(1 for n in shared if amap[n]["move"] != bmap[n]["move"])

    print(f"\nPAIRED COMPARISON on {len(shared)} shared positions")
    print(f"  (negative favours {b_label}: lower centipawn loss is better)\n")
    print(f"  {a_label:<24} ACPL {a['acpl']:8.1f} cp   agree {a['agreement_pct']:5.1f}%   "
          f"blunders {a['blunder_pct']:5.1f}%   {a['median_ms']:6.0f} ms")
    print(f"  {b_label:<24} ACPL {b['acpl']:8.1f} cp   agree {b['agreement_pct']:5.1f}%   "
          f"blunders {b['blunder_pct']:5.1f}%   {b['median_ms']:6.0f} ms")
    print(f"\n  paired difference   {mean:+8.2f} cp   (se {se:.2f}, sd {sd:.1f})")
    print(f"  95% CI              [{lo:+.2f}, {hi:+.2f}] cp")
    print(f"  t = {t:+.2f}   p = {p:.4f}")
    print(f"  moves differing     {changed}/{len(shared)} ({changed/len(shared)*100:.1f}%)")

    print()
    if p < 0.05:
        better = b_label if mean < 0 else a_label
        print(f"  SIGNIFICANT at alpha=0.05 — {better} is stronger on this suite.")
    else:
        need = n_for_delta(sd, 20)
        print(f"  NOT SIGNIFICANT. This does NOT mean the arms are equal — it means this")
        print(f"  experiment could not tell. Resolving a 20cp difference at this variance")
        print(f"  needs {need} paired positions; you ran {len(shared)}.")
        detectable = 2.8 * sd / math.sqrt(len(shared))
        print(f"  Smallest difference {len(shared)} positions could detect: ~{detectable:.0f} cp.")


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)

    default_workers = max(1, (os.cpu_count() or 4) - 2)

    b = sub.add_parser("build", help="generate and cache the frozen position suites")
    b.add_argument("--games", type=int, default=700)
    b.add_argument("--per-game", type=int, default=2)
    b.add_argument("--mate", action="store_true", default=True,
                   help="also collect mate-in-1 positions")
    b.add_argument("--workers", type=int, default=default_workers)

    r = sub.add_parser("run", help="measure ACPL for one engine configuration")
    r.add_argument("label")
    r.add_argument("--sims", type=int, default=600)
    r.add_argument("--workers", type=int, default=default_workers)
    r.add_argument("--threads", type=int, default=1)
    r.add_argument("--limit", type=int, default=None)
    r.add_argument("--uniform", action="store_true",
                   help="positive control: search with no network (uniform priors). "
                        "Must measure clearly worse; if it does not, the harness has "
                        "no power and its null results mean nothing.")

    m = sub.add_parser("mate", help="mate-in-1 detection rate")
    m.add_argument("label")
    m.add_argument("--sims", type=int, default=200)
    m.add_argument("--workers", type=int, default=default_workers)
    m.add_argument("--threads", type=int, default=1)
    m.add_argument("--limit", type=int, default=None)

    c = sub.add_parser("compare", help="paired comparison of two runs")
    c.add_argument("a_label")
    c.add_argument("b_label")

    args = ap.parse_args()
    if args.cmd == "build":
        build(args.games, args.per_game, args.mate, args.workers)
    elif args.cmd == "run":
        cmd_run(args.label, args.sims, args.workers, args.threads, args.limit,
                args.uniform)
    elif args.cmd == "mate":
        cmd_mate(args.label, args.sims, args.workers, args.threads, args.limit)
    else:
        cmd_compare(args.a_label, args.b_label)


if __name__ == "__main__":
    main()
